runtime: python27
api_version: 1
threadsafe: true

manual_scaling:
  instances: 1

# Comment out when pushing to prod
resources:
 cpu: .5
 memory_gb: 0.18
 disk_size_gb: 10

libraries:
  - name: lxml
    version: 3.7.3

handlers:
# Able to read html file to update values.
- url: /html
  static_dir: html
  application_readable: true
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /data
  static_dir: data
  application_readable: true
- url: /templates
  static_dir: templates
  application_readable: true
- url: /.*
  script: main.app
